version: '3.7'
services:
  tgbot:
    container_name: tgbot
    image: ${DOCKER_IMAGE}
    restart: always
    depends_on:
      - fluentbit
      - postgresql
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: app.logs

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tgeasybot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/yc-user/dbdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  fluentbit:
    container_name: fluentbit
    image: cr.yandex/yc/fluent-bit-plugin-yandex:v1.0.3-fluent-bit-1.8.6
    ports:
      - 24224:24224
      - 24224:24224/udp
    restart: always
    environment:
      YC_GROUP_ID: ${LOG_GROUP_ID}
    volumes:
      - /etc/fluentbit/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
      - /etc/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf

x-yc-disks:
  - device_name: dbdata
    fs_type: ext4
    host_path: /home/yc-user/dbdata