db:
  port: 6432
  user: user
  database: tgeasybot
  certfile: "root.crt"
  deprecate: 1m

tgapi:
  address: "https://api.telegram.org/"

timer:
  period: 10s

poller:
  period: 1s

worker:
  period: 1s
  workers: 1